module.exports = {
    mainInfo: {
        parentCategory: '',
        category: '',
        description: 'Generated by automation test',
        status: 'Chưa sử dụng',
        isPrinted: false,
        model: '',
        serial: '',
        manufacturerId: '',
        originId: '',
        supplier: ''
    },
    managementInfo: {
        ownerId: '',
        locationId: '',
        departmentId: '',
        userUsing: ''
    },
    financialInfo: {
        invoiceNo: '',
        purchaseDate: '',
        usageDate: '',
        outOfSystemDate: '',
        foreignCurrency: false,
        price: 0,
        currencyRate: 1,
        decommisionPrice: 0
    },
    depreciationInfo: {
        autoDepreciation: false,
        depreciationTime: 0,
        depreciationStartDate: '',
        depreciationEndDate: ''
    },
    maintenanceInfo: {
        expirationDate: '',
        warrantyEndDate: '',
        maintenanceSchedule: 'Chu kỳ',
        maintenanceUserName: '',
        maintenanceUserEmail: ''
    }
}